### ISSUE TITLE
Rework form dropdowns somehow to disallow labels to be inserted 

### ISSUE THREAD

**Issue by asa-leholland** [team-cs-cats/cimdb#41]
Inserting a record with an attribute from a dropdown inserts the string of the first dropdown option. Need to find a way to rework the dropdowns so that the default 'selected' label does not insert into the table if no dropdown selection is made.

For example, on Add New Site feature on Site Management page, if no State is selected, the database enters: "Select State:" as the state field in the table upon insert.

**Comment by asa-holland** [comment]
Fixed as a result of #51
